src/template/urls.py
from django.urls import path

from template import views

urlpatterns = [
    path('<int:pk>', views.TemplateDetail.as_view(), name='template'),
    path('create/', views.TemplateCreate.as_view(), name='template_create'),
    path('preview/<int:pk>', views.TemplatePreview.as_view(), name='template_preview'),
    path('delete/<int:pk>', views.TemplateDelete.as_view(), name='template_delete'),
    path('list/<int:user>', views.TemplateList.as_view(), name='template_list'),
]

src/templater/urls.py
from templater import admin
from django.urls import path, include
from template.views import TemplateList
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('accounts/', include('custom_auth.urls')),
    path('templates/', include('template.urls')),
    path('', TemplateList.as_view(), name='home'),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/template/models.py
from os.path import relpath
from django.db import models
from django.conf import settings
from django.utils.translation import ugettext_lazy as _

from custom_auth.models import User
from template.validators import TemplateNameValidator
from template.utils import create_thumbnail, make_thumbnail_save_path
from template.validators import HtmlExtensionValidator


def _user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    if instance.user is None:
        return 'anonymous/{0}'.format(filename)
    else:
        return 'user_{0}/{1}'.format(instance.user.id, filename)


class Template(models.Model):
    """
    Template document and information represents by this model.

    Name and file are required. User owner sets automatic,
    but can be set manually by superuser at object creating through admin site.
    """
    name_validator = TemplateNameValidator()

    name = models.CharField(
        _('template name'),
        max_length=150,
        unique=False,
        help_text=_('Required. 150 characters or fewer. Letters, digits, whitespaces and @/./+/-/_ only.'),
        validators=[name_validator]
    )
    user = models.ForeignKey(
        User,
        models.SET_NULL,
        verbose_name=_('owner'),
        null=True,
        blank=True,
    )
    file = models.FileField(
        _('template file'),
        upload_to=_user_directory_path,
        validators=[HtmlExtensionValidator()]
    )
    email = models.EmailField(
        _('email address'),
        max_length=150,
        blank=False,
        help_text=_("Required if owner is anonymous user. Email allows to identify him in future.")
    )
    is_shared = models.BooleanField(
        _('is shared'),
        blank=False,
        default=False,
        help_text=_("This flag make template available to other user.")
    )
    description = models.TextField(
        _('description'),
        null=True,
        blank=True
    )

    class Meta:
        verbose_name = _('template')
        verbose_name_plural = _('templates')

    def __str__(self):
        return self.name

    def delete(self, using=None, keep_parents=False):
        try:
            self.file.storage.delete(self.helper.thumbnail)
        except TemplateHelper.DoesNotExist:
            self.file.storage.delete(make_thumbnail_save_path(self.file.path))
        self.file.delete()
        return super().delete(using, keep_parents)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        super().save(force_insert, force_update, using, update_fields)
        try:
            if self.helper.is_reuploaded:
                self.file.storage.delete(self.helper.thumbnail)
                self.file.storage.delete(self.helper.file)
                self.helper.thumbnail = create_thumbnail(self.file.path)
                self.helper.file = self.file.path
                self.helper.is_reuploaded = False
                self.helper.save()
        except TemplateHelper.DoesNotExist:
            TemplateHelper.objects.create(
                template=self,
                thumbnail=create_thumbnail(self.file.path),
                file=self.file.path,
                is_reuploaded=False
            )


class TemplateHelper(models.Model):
    template = models.OneToOneField(
        Template,
        on_delete=models.CASCADE,
        related_name='helper',
        primary_key=True
    )
    thumbnail = models.CharField(
        max_length=260,
        blank=True,
        null=True,
        default=None
    )
    file = models.CharField(
        max_length=260,
        blank=True,
        null=True,
        default=None
    )
    is_reuploaded = models.BooleanField(
        blank=False,
        default=False
    )

    @property
    def thumbnail_media(self):
        return relpath(self.thumbnail, settings.MEDIA_ROOT)

    class Meta:
        verbose_name = _('template meta')
        verbose_name_plural = _('templates meta')

    def __str__(self):
        return "'{}'-{}".format(
            self.template.name,
            _('meta')
        )

src/templates/site/template/template_creation_form.html
{% extends 'site/create_base.html' %}
{% load i18n %}

{% block title %}
    {% if user.is_anonymous %}
        {{ title_anon }}
    {% else %}
        {{ block.super }}
    {% endif %}
{% endblock %}

{% block content_title %}
    <h1>
        {% if user.is_anonymous %}
            {{ title_anon }}
        {% else %}
            {{ block.super }}
        {% endif %}
    </h1>
{% endblock %}

{% block form_top %}
    {% if user.is_anonymous %}
        <p>{% trans "Enter a template name, your email and choose file to share." %}</p>

    {% else %}
        <p>{% trans "Enter a template name and choose file to upload." %}</p>
    {% endif %}
{% endblock %}

{% block default_submit_title %}
    {% if user.is_anonymous %}
        {% trans 'Share' %}
    {% else %}
        {% trans 'Upload' %}
    {% endif %}
{% endblock %}

src/templates/site/template/template_delete_confirmation_form.html
{% extends 'site/base.html' %}
{% load i18n static %}

{% block extrahead %}
    <script type="text/javascript" src="{% static 'admin/js/cancel.js' %}"></script>
{% endblock %}

{% block bodyclass %}{{ block.super }} delete-confirmation{% endblock %}

{% block content_title %}<h1>{% trans 'Are you sure?' %}</h1>{% endblock %}

{% block content %}
    <p>{% blocktrans with name=object.name %}Are you sure you want to delete the "{{ name }}"?{% endblocktrans %}</p>
    <form method="post">{% csrf_token %}
        <div>
            <input type="submit" value="{% trans "Yes, I'm sure" %}">
            <a href="{% url 'template' pk=object.pk %}" class="button cancel-link">{% trans "No, take me back" %}</a>
        </div>
    </form>
{% endblock %}

src/templates/site/template/template_detail_form.html
{% extends 'site/base.html' %}
{% load i18n staticfiles %}

{% block title %}
    {{ object.name }}
{% endblock %}

{% block extrastyle %}

    <link rel="stylesheet" href="{% static 'admin/css/changelists.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/forms.css' %}">
    <link rel="stylesheet" href="{% static 'site/css/grid.css' %}">

{% endblock %}

{% block extrahead %}
    <script type="text/javascript">
        let readonly;
        let textfield;
        let editButton;
        let cancelButton;
        let saveButton;
        let fileFieldset;

        function createTextField() {
            textfield = document.createElement("textarea");
            textfield.id = "id_description";
            textfield.name = "description";
            textfield.className = "vLargeTextField";
            textfield.cols = "40";
            textfield.rows = "10";
            textfield.value = readonly.innerHTML;
        }

        function createCancelButton() {
            cancelButton = document.createElement("input");
            cancelButton.id = "cancel-button";
            cancelButton.type = "button";
            cancelButton.value = "{% trans 'Cancel' %}";
            cancelButton.className = "icon cancel";
            cancelButton.setAttribute("onclick", "enableEditor(false)");
        }

        function createSaveButton() {
            saveButton = document.createElement("input");
            saveButton.id = "save-button";
            saveButton.type = "submit";
            saveButton.name = "_edit";
            saveButton.value = "{% trans 'Save' %}";
            saveButton.className = "icon save";
        }

        function enableEditor(enable) {
            if(enable) {
                readonly = document.getElementById("id_description");
                fileFieldset = document.getElementById("file_fieldset");
                fileFieldset.hidden = false;
                if (textfield == null) {
                    createTextField();
                }
                readonly.parentNode.replaceChild(textfield, readonly);

                if (editButton == null) {
                    editButton = document.getElementById("edit-button");
                }
                if (cancelButton == null) {
                    createCancelButton();
                }
                if (saveButton == null) {
                    createSaveButton();
                }
                editButton.parentNode.replaceChild(cancelButton, editButton);
                cancelButton.parentNode.insertBefore(saveButton, cancelButton);
            }
            else {
                textfield.parentNode.replaceChild(readonly, textfield);
                cancelButton.parentNode.replaceChild(editButton, cancelButton);
                editButton.parentNode.removeChild(saveButton);
                fileFieldset.hidden = true;
            }
        }
    </script>
{% endblock %}

{% block coltype %}flex{% endblock %}
{% block content %}
    <div id="content-main">
        <h1 class="mobile-text-center">"{{ object.name }}" {% trans 'by' %} {% firstof object.user.username object.email %}</h1>
        <ul class="object-tools">
            <li>
                <a href="{% url 'template_preview' pk=object.pk %}" class="icon preview mo-mobile">{% trans 'Preview' %}</a>
            </li>
            <li>
                <a href="{{ MEDIA_URL }}{{ object.file.name }}" class="icon download" download>{% trans 'Download' %}</a>
            </li>
        </ul>
        <div class="template-thumbnail">
            <img src="{{ MEDIA_URL }}{{ object.helper.thumbnail_media }}"
                 onerror="
                     this.onerror = null;
                     this.src = '{% static 'site/img/html-logo.jpg' %}';
                 "/>
        </div>
        <form enctype="multipart/form-data" id="action-form" method="post">{% csrf_token %}
            <fieldset class="module aligned" style="margin-top: 25px">
                <h2>{% trans 'Template info' %}</h2>
                <div class="form-row field-description">
                    <div>
                        <label for="id_description">{% trans 'Descriprion:' %}</label>
                        <div id="id_description" class="readonly">{{ object.description|default:_("No description") }}</div>
                    </div>
                </div>
            </fieldset>
            <fieldset id="file_fieldset" class="module aligned " hidden>
                <h2>{% trans 'Media files' %}</h2>
                <div class="form-row field-file">
                    <div>
                        <label for="id_file">{% trans 'File' %}:</label>
                        <p class="file-upload">
                            <input type="file" name="file" id="id_file">
                        </p>
                    </div>
                </div>
            </fieldset>
            {% if is_owner or user.is_staff %}
                <div class="submit-row">
                    <p class="deletelink-box"><a href="{% url 'template_delete' pk=object.pk %}" class="deletelink icon delete">{% trans 'Delete' %}</a></p>
                    {% if is_owner %}
                        {% if object.is_shared %}
                            <input type="submit" value="{% trans 'Hide' %}" class="default icon lock" name="_hide">
                        {% else %}
                            <input type="submit" value="{% trans 'Share' %}" class="default icon share" name="_share">
                        {% endif %}
                        <input id="edit-button"
                               type="button"
                               value="{% trans 'Edit' %}"
                               class="icon edit"
                               onclick="enableEditor(true)">
                    {% endif %}
                </div>
            {% endif %}
        </form>
    </div>
{% endblock %}

src/templates/site/template/template_list_form.html
{% extends 'site/base.html'%}
{% load i18n staticfiles %}

{% block extrastyle %}

	<link rel="stylesheet" href={% static 'site/css/grid.css' %}>
    <link rel="stylesheet" href={% static 'admin/css/changelists.css' %}>

{% endblock %}

{% block content %}
    <div class="module" id="changelist">
        <div id="toolbar" class="unordered">
            <form id="changelist-search" method="get"><div>
                <label for="searchbar"><img src="{% static "admin/img/search.svg" %}" alt="Search"></label>
                <input type="text" size="40" name="{{ search_var }}" value="{{ search_query }}" id="searchbar" autofocus>
                <input type="submit" value="{% trans 'Search' %}">
                {% if search_query %}
                <span class="small quiet">
                    <a href="?">
                        {% trans "Show all" %}
                    </a>
                </span>
                {% endif %}
            </div>
            </form>
        </div>
        {% if object_list %}
            <div class="grid-wrapper">
                {% for template in object_list %}
                    <div class="grid-box with-margin visible float-inline quarter">
                        <div class="template-cell">
                            <a href="{% url 'template' pk=template.pk %}">
                                <img src="{{ MEDIA_URL }}{{ template.helper.thumbnail_media }}"
                                     onerror="
                                         this.onerror = null;
                                         this.src = '{% static 'site/img/html-logo.jpg' %}';
                                     "/>
                                <p class="text-center">{{ template.name }}</p>
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
            {% if is_paginated %}
                <p class="paginator">
                    <span class="page-links">
                        {% if page_obj.has_previous %}
                            <a href="?page={{ page_obj.previous_page_number }}{% if search_query %}&{{ search_var }}={{ search_query }}{% endif %}">{% trans 'Previous' %}</a>
                        {% endif %}
                        <span class="page-current with-margin">
                            {% blocktrans with n=page_obj.number p=page_obj.paginator.num_pages %}Page {{ n }} of {{ p }}
                            {% endblocktrans %}
                        </span>
                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}{% if search_query %}&{{ search_var }}={{ search_query }}{% endif %}">{% trans 'Next' %}</a>
                        {% endif %}
                    </span>
                </p>
            {% endif %}
        {% else %}
            {% if search_query %}
                <h1 class="text-center">{% trans 'There are no results for your request' %}</h1>
            {% else %}
                <h1 class="text-center">{% trans 'Sorry... There are no templates yet :(' %}</h1>
            {% endif %}
        {% endif %}
    </div>
{% endblock %}

src/templates/site/template/template_preview_form.html
{% extends 'site/base.html' %}

{% block extrastyle %}
    <style>
        #content {
            padding: unset !important;
        }
    </style>
{% endblock %}

{% block extrahead %}
    <script>

        function adjustSize(iframe) {
            iframe.style.width = 100 + '%';
            iframe.style.height = iframe.contentWindow.outerHeight + 'px';
        }
    </script>
{% endblock %}

{% block content %}
    <iframe src="{{ MEDIA_URL }}{{ file }}" frameborder="0" onload="adjustSize(this);"></iframe>
{% endblock %}

{% block footer %}{% endblock %}